services:
  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    command: ["npm", "run", "start:client"]
    ports:
      - 3000:3000
    networks:
      - classroom

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    command: ["npm", "run", "start:server"]
    ports:
      - '3333-3334:3333-3334'
    networks:
      - classroom

networks:
  classroom:
    driver: bridge
